# Generated by Django 5.0.2 on 2024-02-15 03:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getotp', '0003_alter_otprequest_channel_alter_otprequest_valid_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='channel',
            field=models.CharField(choices=[('Android', 'Android'), ('iOS', 'iOS'), ('Web', 'Web')], max_length=50, verbose_name='Channel'),
        ),
        migrations.AlterField(
            model_name='otprequest',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 3, 1, 52, 802331, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='otprequest',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 3, 3, 52, 802331, tzinfo=datetime.timezone.utc)),
        ),
    ]
