# Generated by Django 5.0.2 on 2024-02-15 04:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getotp', '0004_alter_otprequest_channel_alter_otprequest_valid_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 4, 5, 24, 668731, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='otprequest',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 4, 7, 24, 668731, tzinfo=datetime.timezone.utc)),
        ),
    ]
